apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-v3
  name: frontend-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-v3
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-v3
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - image: acrpaypal1783519282.azurecr.io/frontend:v3
        name: frontend
        ports:
        - containerPort: 3001
        resources: {}
status: {}
